const BEGIN_MARKER: &str = "<!-- BEGIN CUTTLEFISH-MANAGED -->";
const END_MARKER: &str = "<!-- END CUTTLEFISH-MANAGED -->";
const AUTO_COMMENT: &str =
    "<!-- Auto-generated by Cuttlefish. Manual edits inside this block will be overwritten. -->";

fn wrap(content: &str) -> String {
    format!("{BEGIN_MARKER}\n{AUTO_COMMENT}\n\n{content}\n{END_MARKER}\n")
}

pub fn upsert(existing: &str, content: &str) -> String {
    let section = wrap(content);

    if existing.is_empty() {
        return section;
    }

    if let (Some(begin), Some(end)) = (existing.find(BEGIN_MARKER), existing.find(END_MARKER)) {
        if begin < end {
            let end_of_marker = existing[end..].find('\n').map_or(existing.len(), |i| end + i + 1);
            let mut result = String::new();
            result.push_str(&existing[..begin]);
            result.push_str(&section);
            let after = &existing[end_of_marker..];
            if !after.is_empty() {
                result.push_str(after);
            }
            if !result.ends_with('\n') {
                result.push('\n');
            }
            return result;
        }
    }

    let mut result = existing.to_string();
    if !result.ends_with('\n') {
        result.push('\n');
    }
    result.push('\n');
    result.push_str(&section);
    result
}

pub fn has_managed_section(content: &str) -> bool {
    content.contains(BEGIN_MARKER) && content.contains(END_MARKER)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_upsert_into_empty_file() {
        let result = upsert("", "new content");
        assert_eq!(
            result,
            "<!-- BEGIN CUTTLEFISH-MANAGED -->\n\
             <!-- Auto-generated by Cuttlefish. Manual edits inside this block will be overwritten. -->\n\
             \n\
             new content\n\
             <!-- END CUTTLEFISH-MANAGED -->\n"
        );
    }

    #[test]
    fn test_upsert_appends_to_existing_content() {
        let existing = "# My Project\n\nSome user content.\n";
        let result = upsert(existing, "managed stuff");
        assert!(result.starts_with("# My Project\n\nSome user content.\n"));
        assert!(result.contains("<!-- BEGIN CUTTLEFISH-MANAGED -->"));
        assert!(result.contains("managed stuff"));
        assert!(result.contains("<!-- END CUTTLEFISH-MANAGED -->"));
    }

    #[test]
    fn test_upsert_replaces_existing_managed_section() {
        let existing = "# My Project\n\n\
            <!-- BEGIN CUTTLEFISH-MANAGED -->\n\
            <!-- Auto-generated by Cuttlefish. Manual edits inside this block will be overwritten. -->\n\
            \n\
            old content\n\
            <!-- END CUTTLEFISH-MANAGED -->\n\n\
            User content after.\n";
        let result = upsert(existing, "new content");
        assert!(result.contains("new content"));
        assert!(!result.contains("old content"));
        assert!(result.contains("User content after."));
    }

    #[test]
    fn test_has_managed_section() {
        assert!(!has_managed_section("# Just a readme"));
        assert!(has_managed_section(
            "stuff\n<!-- BEGIN CUTTLEFISH-MANAGED -->\nfoo\n<!-- END CUTTLEFISH-MANAGED -->\n"
        ));
    }
}
